### ISSUE TITLE
Need a way to use the -dtoken parameter

### ISSUE THREAD

**Issue by LuigiBox** [ZachNo/Blockland-AdvancedSM#1]
I don't know if you're still around, let alone willing to fix this.
But I really enjoy using this tool, and sadly after the recent authentication update, this no longer works. As you won't be able to post to the master server without the dtoken.

**Comment by ZachNo** [comment]
Updated the program to have a dtoken field in 0.9.5
https://github.com/ZachNo/Blockland-AdvancedSM/releases/tag/0.9.5
